version: "3.4"

services:
  postgresql_database: 
    image: postgres
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=productDb
    ports: 
      - "5431:5431"
    restart: always
    volumes: 
      - database-data/var/lib/postgresql/data/

  pgadmin4:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgmail.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports: 
      - "5050:80"
    restart: always
    volumes: 
      - pgadmin:/root/.pgadmin
volumes: 
  database-data:
  pgadmin: 
